name: auto-testing
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
jobs:
  run:
    runs-on: [ubuntu-latest]
    steps:
      - uses: actions/checkout@v2
      - name: sanity-check
        env:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
        run: |
          pip install -r requirements.txt
      - name: test-cases
        run: |
          python test.py